[package]
name = "ping_squirrel"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = "0.12.1"

[build-dependencies]
phf-codegen = "0.12.1" 
reqwest = { version = "0.12", features = ["blocking"] } 
