[package]
name = "ping_squirrel"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = "0.12.1"
tokio = { version = "1.46.1", features = ["full"] }

[build-dependencies]
phf_codegen = "0.12.1" 
reqwest = { version = "0.12", features = ["blocking"] } 
